### ISSUE TITLE
Failed to build iOS app (swift)

### ISSUE THREAD

**Issue by Ajit121** [roughike/flutter_facebook_login#106]
Getting this issue:

Xcode's output:
↳
    /Users/ajit/AndroidProjects/grab_loyalty/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/FBSDKLoginCompletion.m:136:51: error: property 'isActive' not found on object of type 'FBSDKApplicationDelegate *'
        if ([FBSDKApplicationDelegate sharedInstance].isActive) {
                                                      ^
    /Users/ajit/AndroidProjects/grab_loyalty/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/Internal/FBSDKLoginCompletion.m:223:49: error: property 'isActive' not found on object of type 'FBSDKApplicationDelegate *'
      if ([FBSDKApplicationDelegate sharedInstance].isActive) {
                                                    ^
    2 errors generated.
    /Users/ajit/AndroidProjects/grab_loyalty/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.m:552:46: error: no visible @interface for 'FBSDKApplicationDelegate' declares the selector 'openURL:sender:handler:'
      [[FBSDKApplicationDelegate sharedInstance] openURL:authURL sender:self handler:^(BOOL openedURL, NSError *anError) {
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/ajit/AndroidProjects/grab_loyalty/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.m:595:50: error: no visible @interface for 'FBSDKApplicationDelegate' declares the selector 'openURLWithSafariViewController:sender:fromViewController:handler:'
          [[FBSDKApplicationDelegate sharedInstance] openURLWithSafariViewController:authURL
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/ajit/AndroidProjects/grab_loyalty/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.m:600:50: error: no visible @interface for 'FBSDKApplicationDelegate' declares the selector 'openURL:sender:handler:'
          [[FBSDKApplicationDelegate sharedInstance] openURL:authURL sender:self handler:handlerWrapper];
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 errors generated.

**Comment by 9dan** [comment]
Having the same error on  ([FBSDKApplicationDelegate sharedInstance].isActive)

**Comment by dev-mush** [comment]
Ok apparently there isn't a version lock on FBSDKCoreKit (on which FBSDKLoginKit depends), that has been updated to the 4.42.0 version two days ago, so a pod update downloads the latest version which introduces breaking changes and triggers the error above. 
A possible solution would be to lock the version of FBSDKCoreKit in this repo's pubspec.

**Comment by dev-mush** [comment]
I've solved by integrating locally in my project the fix introduced in the #107

**Comment by ronaldbudianto** [comment]
Hi @dev-mush can i know when your fix is release? or is there any fix without waiting your PR?

**Comment by dev-mush** [comment]
@ronaldbudianto I'm not the maintainer of this repo, so the release is set when (and if) the maintainer will accept it I assume :D 

In the meanwhile you could clone it and use it locally or you could import it by referring to the branch of the pr in your pubspec.

**Comment by marcosfons** [comment]
I had the same issue

**Comment by Theunodb** [comment]
Also having this issue

**Comment by auronsan** [comment]
still having this issue
```
                                                  ^
                                                                                                               _Nonnull 
    /Users/anshor/Projects/fluttertour/youn_point_app/ios/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKConstants.h:350:137:
    warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
    [-Wnullability-completeness]
    - (void)attemptRecoveryFromError:(NSError *)error optionIndex:(NSUInteger)recoveryOptionIndex delegate:(id)delegate
    didRecoverSelector:(SEL)didRecoverSelector contextInfo:(void *)contextInfo;
```

**Comment by maks-nuraphone** [comment]
Found the same though needed to also specify extra dependency version on top of what was in #113.
As a **temporary** workaround until either the PRs get merged or the package gets updated to work with the newer API in FB's sdk I am using my fork successfully in an app with:
```
flutter_facebook_login:
    git: 
      url: https://github.com/nura/flutter_facebook_login
      ref: fix-fbsdkcore-version
```

**Comment by laptrinhcomvn** [comment]
Thanks @maks-nuraphone , it works.

**Comment by cerezo074** [comment]
@laptrinhcomvn @maks-nuraphone, sorry if I am annoying, but I couldn't run the fork well, I got an error message. After the "running pod install" message is shown at the console. Could you help me which steps did you do it? I am starting with flutter.

`Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - flutter_facebook_login

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
      In snapshot (Podfile.lock):
        FBSDKLoginKit (= 4.39.1)

      In Podfile:
        flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`) was resolved to 0.0.1, which depends on
          FBSDKLoginKit (= 4.42.0)

    It seems like you've changed the constraints of dependency `FBSDKLoginKit` inside your development pod `flutter_facebook_login`.
    You should run `pod update FBSDKLoginKit` to apply changes you've made.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/resolver.rb:91:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:909:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:907:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/analyzer.rb:114:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:266:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:174:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:173:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:136:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone X.
`

**Comment by cerezo074** [comment]
@maks-nuraphone , I think you need to fix the core version. I could resolve an issue that I had fetching the plugin from your fork just fixing the version of FBSDKCoreKit with the same of FBSDKLoginKit.

Installing FBSDKCoreKit (4.42.0)
Installing FBSDKLoginKit (4.42.0)
